-- ============================================================
-- InsightNest LMS — Seed Data
-- Migration 003: Initial admin, course, modules, lessons
-- ============================================================

-- NOTE: The admin user must be created via Supabase Auth first.
-- Run this AFTER creating the admin auth user.
-- The handle_new_user() trigger will auto-create the profile,
-- then we update it with admin role and enrollment_id.

-- After creating admin user via Auth API, update their profile:
-- (Replace 'ADMIN_USER_UUID' with the actual UUID from auth.users)

-- UPDATE public.profiles
-- SET role = 'admin',
--     enrollment_id = 'ADMIN001',
--     full_name = 'Admin',
--     is_active = true
-- WHERE email = 'admin@insightnest.com';

-- ============================================================
-- Seed Course: GenAI Data Analytics Accelerator
-- ============================================================
-- NOTE: Run after admin user is created and instructor is assigned.
-- These are template INSERT statements. The actual UUIDs will be
-- generated by Supabase. Use the Admin Dashboard UI to create
-- courses in production.

-- Template: Course
-- INSERT INTO public.courses (title, description, is_published, price, duration_weeks)
-- VALUES (
--   'The Generative AI Data Analytics & Engineering Accelerator',
--   'Next-Generation Data Architecture | Powered by Agentic AI & Microsoft Fabric. This high-octane, 4-week intensive builds the next generation of data leaders: AI-Augmented Data Architects.',
--   true,
--   1999,
--   4
-- );

-- Template: Modules (use the course UUID from above)
-- INSERT INTO public.modules (course_id, title, description, sort_order) VALUES
-- ('COURSE_UUID', 'Week 1: AI-Augmented Analytics & Quantitative Foundations', 'Core Stack: Intelligent Excel + Generative Statistical Modeling', 1),
-- ('COURSE_UUID', 'Week 2: Autonomous Code Compilation & Visual Intelligence', 'Core Stack: AI-First Python + Dynamic Visualization Engine', 2),
-- ('COURSE_UUID', 'Week 3: The Generative BI Command Center', 'Core Stack: Power BI + Generative DAX + Microsoft Fabric', 3),
-- ('COURSE_UUID', 'Week 4: Enterprise AI Architecture & Capstone Deployment', 'Core Stack: Microsoft Fabric Lakehouse + Autonomous Analytics Pipeline', 4);

-- Template: Lessons (use the module UUIDs from above)
-- Week 1 Lessons
-- INSERT INTO public.lessons (module_id, title, type, sort_order, duration_minutes) VALUES
-- ('MODULE1_UUID', 'Prompt-Engineered Data Ingestion', 'video', 1, 45),
-- ('MODULE1_UUID', 'AI-Formulated Logic: INDEX MATCH & XLOOKUP', 'video', 2, 60),
-- ('MODULE1_UUID', 'Generative Statistical Modeling', 'video', 3, 50),
-- ('MODULE1_UUID', 'Week 1 Practice Notes', 'notes', 4, 0);

-- Template: Assignments
-- INSERT INTO public.assignments (course_id, module_id, title, instructions, max_marks, deadline) VALUES
-- ('COURSE_UUID', 'MODULE1_UUID', 'The Revenue Architecture Engine', 'Build an Excel-based financial dashboard utilizing LLM schema mapping logic.', 100, now() + interval '7 days'),
-- ('COURSE_UUID', 'MODULE2_UUID', 'Global Media Ecosystem Simulator', 'Construct a programmatic Python data story utilizing ChatGPT/Copilot code compilation.', 100, now() + interval '14 days');

-- Template: Quizzes
-- INSERT INTO public.quizzes (course_id, module_id, title, passing_percentage, total_marks, is_published) VALUES
-- ('COURSE_UUID', 'MODULE1_UUID', 'Week 1: Excel & Statistics Quiz', 60, 50, true);

-- Template: Quiz Questions
-- INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_option, marks, sort_order) VALUES
-- ('QUIZ_UUID', 'What function would you use for fuzzy matching in Excel?', '["VLOOKUP", "XLOOKUP", "INDEX MATCH", "SUMIF"]', 2, 5, 1),
-- ('QUIZ_UUID', 'Which AI model is best suited for schema mapping?', '["GPT-4", "DALL-E", "Whisper", "Codex"]', 0, 5, 2);

-- ============================================================
-- NOTE: Use the Admin Dashboard to create and manage all data.
-- These templates are for reference only.
-- ============================================================
